import { AssetType } from './asset'
import { ItemSpellTrigger, Map, Query } from './types'

export const ENV = {
  DEV: 'DEV',
  TEST: 'TEST',
  PROD: 'PROD',
}

export const SPELL = 'SPELL'
export const ITEM = 'ITEM'
export const NPC = 'NPC'
export const ACHIEVEMENT = 'ACHIEVEMENT'
export const UNNAMED = 'UNNAMED'

export const DEFAULT_MOD = 'BASEMOD'

export const DEFAULT_SPELL_BASE = 133
export const DEFAULT_SPELL_NAME = 'Spell'
export const DEFAULT_ICON_SPELL_BASE = 56247

export const DEFAULT_SPELL_DESCRIPTION = 'A spell.'
export const DEFAULT_SPELL_AURA_DESCRIPTION = 'An aura.'

export const DEFAULT_ITEM_BASE = 0 // FIXME: add real item id
export const DEFAULT_ITEM_NAME = 'Item'

export const DEFAULT_NPC_BASE = 0 // FIXME: add real npc id
export const DEFAULT_NPC_NAME = 'Npc'

export const DEFAULT_MOUNT_NPC_BASE = 308 // FIXME: add real npc id

export const DEFAULT_DIRECT_SPELL_BASE = 133 // FIXME: add real npc id

export const WARRIOR = 'WARRIOR'
export const ROGUE = 'ROGUE'
export const DRUID = 'DRUID'
export const MAGE = 'MAGE'
export const WARLOCK = 'WARLOCK'
export const SHAMAN = 'SHAMAN'
export const PRIEST = 'PRIEST'
export const PALADIN = 'PALADIN'
export const HUNTER = 'HUNTER'

export const CLASS_MASKS: Map<number> = {
  [WARRIOR]: 1,
  [PALADIN]: 2,
  [HUNTER]: 4,
  [ROGUE]: 8,
  [PRIEST]: 16,
  [SHAMAN]: 64,
  [MAGE]: 128,
  [WARLOCK]: 256,
  [DRUID]: 1024,
}

export const CLASS_IDS: Map<number> = {
  [WARRIOR]: 1,
  [PALADIN]: 2,
  [HUNTER]: 3,
  [ROGUE]: 4,
  [PRIEST]: 5,
  [SHAMAN]: 7,
  [MAGE]: 8,
  [WARLOCK]: 9,
  [DRUID]: 11,
}

export const HUMAN = 'HUMAN'
export const ORC = 'ORC'
export const DWARF = 'DWARF'
export const NIGHT_ELF = 'NIGHT_ELF'
export const UNDEAD = 'UNDEAD'
export const TAUREN = 'TAUREN'
export const GNOME = 'GNOME'
export const TROLL = 'TROLL'
export const BLOOD_ELF = 'BLOOD_ELF'
export const DRAENEI = 'DRAENEI'

export const RACE_MASKS: Map<number> = {
  [HUMAN]: 1,
  [ORC]: 2,
  [DWARF]: 4,
  [NIGHT_ELF]: 8,
  [UNDEAD]: 16,
  [TAUREN]: 32,
  [GNOME]: 64,
  [TROLL]: 128,
  [BLOOD_ELF]: 512,
  [DRAENEI]: 1024,
}

export const RACE_IDS: Map<number> = {
  [HUMAN]: 1,
  [ORC]: 2,
  [DWARF]: 3,
  [NIGHT_ELF]: 4,
  [UNDEAD]: 5,
  [TAUREN]: 6,
  [GNOME]: 7,
  [TROLL]: 8,
  [BLOOD_ELF]: 10,
  [DRAENEI]: 11,
}

export const ASSET_TYPE: Map<AssetType> = {
  SPELL: SPELL,
  ITEM: ITEM,
  NPC: NPC,
  ACHIEVEMENT: ACHIEVEMENT,
}

export const SCHOOLS = {
  FIRE: 'FIRE',
  FROST: 'FROST',
  NATURE: 'NATURE',
  SHADOW: 'SHADOW',
  HOLY: 'HOLY',
  ARCANE: 'ARCANE',
}

export const BASE_MOUNT_SPEED = 80

export const CREATE_ACHIEVEMENT_TASK = 'CREATE-ACHIEVEMENT'
export const CREATE_ENCHANT_TASK = 'CREATE-ENCHANT'
export const CREATE_ITEM_TASK = 'CREATE-ITEM'
export const CREATE_GEM_TASK = 'CREATE-GEM'
export const CREATE_NPC_TASK = 'CREATE-NPC'
export const CREATE_MODIFIER_TASK = 'CREATE-MODIFIER'
export const CREATE_MOUNT_TASK = 'CREATE-MOUNT'
export const CREATE_PET_TASK = 'CREATE-PET'
export const CREATE_PROFESSION_TASK = 'CREATE-PROFESSION'
export const CREATE_SPELL_TASK = 'CREATE-SPELL'
export const CREATE_STAT_TASK = 'CREATE-STAT'
export const CREATE_SUMMON_TASK = 'CREATE-SUMMON'
export const SETUP_CHARACTER_CREATION_TASK = 'SETUP-CHARACTER-CREATION'
export const GENERATE_EQUIPMENT_TASK = 'GENERATE-EQUIPMENT'
export const SETUP_CLASS_DRUID_TASK = 'SETUP-CLASS-DRUID'
export const SETUP_CLASS_HUNTER_TASK = 'SETUP-CLASS-HUNTER'
export const SETUP_CLASS_MAGE_TASK = 'SETUP-CLASS-MAGE'
export const SETUP_CLASS_PALADIN_TASK = 'SETUP-CLASS-PALADIN'
export const SETUP_CLASS_PRIEST_TASK = 'SETUP-CLASS-PRIEST'
export const SETUP_CLASS_ROGUE_TASK = 'SETUP-CLASS-ROGUE'
export const SETUP_CLASS_SHAMAN_TASK = 'SETUP-CLASS-SHAMAN'
export const SETUP_CLASS_WARLOCK_TASK = 'SETUP-CLASS-WARLOCK'
export const SETUP_CLASS_WARRIOR_TASK = 'SETUP-CLASS-WARRIOR'
export const CREATE_DIRECT_SPELL_TASK = 'CREATE-DIRECT-SPELL'
export const CREATE_EFFECT_OVER_TIME_SPELL_TASK = 'CREATE-EFFECT-OVER-TIME-SPELL'
export const CREATE_RANGED_SPELL_TASK = 'CREATE-RANGED-SPELL'
export const SETUP_SKILLS_TASK = 'SETUP-SKILLS'
export const CREATE_CONSUMABLE_TASK = 'CREATE-CONSUMABLE'
export const CREATE_TALENT_TASK = 'CREATE-TALENT'
export const CREATE_TABLE_TASK = 'CREATE-TABLE'
export const INSERT_SERVER_DATA_TASK = 'INSERT-SERVER-DATA'
export const INSERT_CLIENT_DATA_TASK = 'INSERT-CLIENT-DATA'

export const QUERY_ID = 'QUERY-ID'
export const QUERY_ICON = 'QUERY-ICON'
export const QUERY_EFFECT_POINTS = 'QUERY-EFFECT-POINTS'
export const QUERY_MOUNT_NPC = 'QUERY-MOUNT-NPC'
// FIXME: implement these
export const QUERY_DIRECT_SPELL = 'QUERY-DIRECT-SPELL'
export const QUERY_ENCHANT = 'QUERY-ENCHANT'
export const QUERY_GEM = 'QUERY-GEM'
export const QUERY_MODIFIER = 'QUERY-MODIFIER'

export const DEFAULT_ICON_QUERY: Query<typeof QUERY_ICON> = {
  query: QUERY_ICON,
  subquery: SPELL,
  id: DEFAULT_ICON_SPELL_BASE,
}

export const MAX_ITEM_SPELL_COUNT = 5

export const ITEM_SPELL_TRIGGER_ON_EQUIP = 'ON_EQUIP'
export const ITEM_SPELL_TRIGGER_ON_USE = 'ON_USE'
export const ITEM_SPELL_TRIGGER_ON_USE_NO_DELAY = 'ON_USE_NO_DELAY'
export const ITEM_SPELL_TRIGGER_CHANCE_ON_HIT = 'CHANCE_ON_HIT'
export const ITEM_SPELL_TRIGGER_SOULSTONE = 'SOULSTONE'
export const ITEM_SPELL_TRIGGER_LEARN_SPELL = 'LEARN_SPELL'

export const DEFAULT_ITEM_SPELL_TRIGGER_ID = 'default'

export const ITEM_SPELL_TRIGGERS: Map<ItemSpellTrigger> = {
  [ITEM_SPELL_TRIGGER_ON_EQUIP]: ITEM_SPELL_TRIGGER_ON_EQUIP,
  [ITEM_SPELL_TRIGGER_ON_USE]: ITEM_SPELL_TRIGGER_ON_USE,
  [ITEM_SPELL_TRIGGER_ON_USE_NO_DELAY]: ITEM_SPELL_TRIGGER_ON_USE_NO_DELAY,
  [ITEM_SPELL_TRIGGER_CHANCE_ON_HIT]: ITEM_SPELL_TRIGGER_CHANCE_ON_HIT,
  [ITEM_SPELL_TRIGGER_SOULSTONE]: ITEM_SPELL_TRIGGER_SOULSTONE,
  [ITEM_SPELL_TRIGGER_LEARN_SPELL]: ITEM_SPELL_TRIGGER_LEARN_SPELL,
}

export const DEFAULT_TABLE_PREFIX = '__'

